//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H3_EF_DB_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class routes
    {
        public int id { get; set; }
        public string fromCode { get; set; }
        public string toCode { get; set; }
        public Nullable<int> airlineId { get; set; }
        public string airportId { get; set; }
    
        public virtual airlines airlines { get; set; }
        public virtual airports airports { get; set; }
    }
}
